# Generated by Django 5.1.7 on 2025-04-17 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.pengguna'),
        ),
        migrations.AddField(
            model_name='content',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='set_view',
            field=models.BooleanField(default=False),
        ),
    ]
